### ISSUE TITLE
Styling 

### ISSUE THREAD

**Issue by cpgb85** [AbobosSoftware/cordova-plugin-brother-label-printer#56] opened 2023-01-30 16:32 UTC
What's the best method for printing labels out in pixels?  I have a dk-2205 label right now, I want to have a label designer on my website, but  there is no clear cut method for converting pixels to whatever this is measured in.

**Comment by arcadius** [comment] 2023-01-30 17:05
Your can use HTML5 canvas.
then
`let dataUrl: string = canvas.toDataURL('image/png');`
you need to extract the base64 encoded image from the dataUrl
Then send that to the printer via the SDK

**Comment by arcadius** [comment] 2023-01-30 17:05
BTW: This is not an issue related to this SDK, so, closing this

**Closed by arcadius** 2023-01-30 17:05 UTC

**Comment by robr2112** [comment] 2023-01-30 17:35
Assuming this plugin is still using v3 APIs, and you’re using iOS SDK, there is a setting in the BRPtouchPrintInfo that controls scaling. I recall it’s called nPrintMode. This setting controls how sdk “scale” the image (or pdf) relative to the current paper size. By default it should be “fit to page”, which scales to the printable area (paper minus margins), and it preserves image aspect  ratio by scaling length and width by same amount. The “original” mode does not scale at all but clips at boundary of printable area. The “fit paper” option scales (with aspect ratio) to fit the paper instead of P/A, which trims the boundary of your image. Usually default Fit Page is best mode to use in general. 

We STRONGLY recommend that you create an image that is close to same size as the paper, to avoid print quality issues caused by scaling. 

If you are working in pixels, you need to consider the resolution of the printer to determine the “actual size” (original size) of your image.
 Here is online user manual, with v3 ios reference to the print settings class:
https://support.brother.com/g/s/es/htmldoc/mobilesdk/reference/ios/brptouchprintinfo.html
